package edu.asu.jmars.layer.map2.custom;

import java.util.ArrayList;

import org.json.JSONException;
import org.json.JSONObject;

import edu.asu.jmars.layer.LayerParameters;
import edu.asu.jmars.layer.map2.MapSource;

public interface CustomMap {
    //Header constants for getting data from headerInformation JSON object
    public static final String ORIG_MIN_LON = "orig_min_lon";
    public static final String ORIG_MAX_LON = "orig_max_lon";
    public static final String ORIG_MIN_LAT = "orig_min_lat";
    public static final String ORIG_MAX_LAT = "orig_max_lat";
    public static final String ORIG_NUM_BANDS = "orig_num_bands";
    public static final String NAME = "name";
    public static final String IS_NUMERIC = "isNumeric";
    public static final String VALID_HEADER_FLAG = "valid_header_flag";
    public static final String WIDTH = "orig_width";
    public static final String HEIGHT = "orig_height";
    public static final String WKT = "orig_wkt";
    public static final String STATUS_UPLOADING = "uploading...";
    public static final String STATUS_PROCESSING = "processing...";
    public static final String STATUS_REPROCESSING = "reprocessing...";
    public static final String STATUS_UPDATING_STATUS = "updating status...";
    public static final String STATUS_READING_HEADER = "analyzing header";
    public static final String STATUS_NOT_STARTED = "not started";
    public static final String STATUS_IN_PROGRESS = "in progress";
    public static final String STATUS_COMPLETE = "complete";
    public static final String STATUS_CANCEL_REQUESTED = "cancel requested";
    public static final String STATUS_CANCELED = "canceled";
    public static final String STATUS_ERROR = "error";
    public static final String STATUS_REPROCESSED = "reprocessed";
    public static final String STATUS_AWAITING_USER_INPUT = "Verify image information";
    public static final String NUM_BANDS = "num_bands";
    public static final String ERROR_MSG = "error_msg";
    public static final String STAGE_HEADER_ANALYZED = "5";
    public static final String STAGE_AWAITING_USER_INPUT = "5";//currently the same as header analyzed. Creating new variable in case that ever changes
    public static final int GEO_INPUT_MANUAL = 1;
    public static final int GEO_INPUT_HEADER = 2;
    public static final int GEO_INPUT_PROMPT = 3;
    public static final int EXTENT_INPUT_GLOBAL = 1;
    public static final int EXTENT_INPUT_REGIONAL = 2;
    public static final int DEGREES_INPUT_EAST = 1;
    public static final int DEGREES_INPUT_WEST = 2;
    public static final int SHAPE_INPUT_OCENTRIC = 1;
    public static final int SHAPE_INPUT_OGRAPHIC = 2;
    public static final String SHAPE_OC = "OC";
    public static final String SHAPE_OG = "OG";
    
    public static final int PROCESSING_OPTION_UPLOAD = 1;
    public static final int PROCESSING_OPTION_MANUAL = 2;
    public static final int PROCESSING_OPTION_PROMPT = 3;
    
    
    
    public void setName(String nameVal);
    public void addIgnoreValue(String ignoreVal);
    public void setUnits(String unitsVal);
    public void setExtent(int extentVal);
    public void setDegrees(int degreesVal);
    public void setNorthLat(String northLatVal);
    public void setSouthLat(String southLatVal);
    public void setWestLon(String westLonVal);
    public void setEastLon(String eastLonVal);
    public void setCitation(String citationVal);
    public void setLinks(String linksVal);
    public void setKeywords(String keywordsVal);
    public void setDescription(String descriptionVal);
    public void setCanonicName(String canonicNameVal);
    public void setCustomMapId(String customMapId);
    public void setBasename(String basenameVal);
    public void setFilename(String filenameVal);
    public void setOriginalNorthLat(String origNorthLatVal);
    public void setOriginalSouthLat(String origSouthLatVal);
    public void setOriginalWestLon(String origWestLonVal);
    public void setOriginalEastLon(String origEastLonVal);
    public void setStatus(String statusVal);
    public void setStage(String stageVal);
    public void setErrorMessage(String errorMsgVal);
    public void setValidHeaderFlag(String validFlag);
    public void setShapeType(int shapeType);
    public void setReprocessParentId(String reprocessid);
    public void setReprocessOriginalCanonicName(String reprocess_origCanonicName);

    public String getReprocessParentId();
    public String getReprocessOriginalCanonicName(); 
    public String getFilename();
    public String getName();
    public String getIgnoreValue();
    public String getUnits();
    public int getExtent();
    public int getDegrees();
    public String getNorthLat();
    public String getSouthLat();
    public String getWestLon();
    public String getEastLon();
    public String getCitation();
    public String getLinks();
    public String[] getKeywords();
    public String getDescription();
    public String getCanonicName();
    public String getCustomMapId();
    public String getBasename();
    public String getOriginalNorthLat();
    public String getOriginalSouthLat();
    public String getOriginalWestLon();
    public String getOriginalEastLon();
    public String getStatus();
    public String getStage();
    public String getErrorMessage();
    public String getWktString();
    public String getNumberOfBands();
    public String getMaxPPD();
    public int getShapeType();
    public String getReprocessOrigUploadName();
    
    //other methods
    public boolean isCanceled();
    public char getWarpMethod();
    public boolean getCornerPointsChanged();
    public void setProcessingStarted(boolean started);
    public void setReprocessingStarted(boolean started);
    public void setSelectedUploadProcess(int process);
    public int getSelectedUploadProcess();
    public boolean hasStartedUpload();
    public boolean isErrorCondition();
    public void startUpload();
    public void setHeaderInformation(JSONObject json) throws JSONException;
    public boolean isValidHeaderFlag();
    public void prepareForOneStepProcessing();
    public boolean checkCapabilitiesRun();
    public void capabilitiesHaveBeenRun();
    public String getUploadDate();
    public String getLastUsedDate();
    public String getOwner();
    public boolean hasProcessingStarted();
    public void setCancelFlag(boolean b);
    public MapSource getGraphicSource();
    public void setLastUsedDate(String format);
    public void formatCornerPoints();
    public boolean isSharedWithOthers();
    public void setupGCPsForCompare();
    public ArrayList<String> getSharedWithUsers();
    public ArrayList<SharingGroup> getSharedWithGroups();
    public String getSharedWithUsersString();
    public String getSharedWithGroupsString();
    public void addSharedUser(String user);
    public void addSharedGroup(SharingGroup group);
//    public void addSelectedGroup(String groupName);
    public void removeSelectedGroup(String groupName);
//    public void addSelectedUser(String username);
    public void removeSelectedUser(String username);
    public void addTempSharedUser(String user);
    public void addTempSharedGroup(SharingGroup group);
    public void removeTempSelectedGroup(String groupName);
    public void removeTempSelectedUser(String username);
//    public void setupTempSharing();
    public ArrayList<SharingGroup> getTempSharedWithGroups();
    public ArrayList<String> getTempSharedWithUsers();
    public boolean hasSharingUserChanges();
    public boolean hasSharingGroupChanges();
    public void updateSharedUsers();
    public void updateSharedGroups();
    public String getKeywordsString();
    public String getShapeTypeString();
    public boolean initialUploadExists();
    public boolean isReprocess();
    public void setReprocess(boolean reprocessVal);
    public void setUploadDate(String uDate);
    public void setLayerParameters(LayerParameters lp);
    public LayerParameters getLayerParameters();
    public boolean isNumeric();
}
